"""racks

Revision ID: eed85fdfa44f
Revises: 
Create Date: 2025-12-20 08:20:35.695828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed85fdfa44f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('racks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('unit_capacity', sa.Integer(), nullable=False),
    sa.Column('energy_consumption_capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number', name='uq_rack_serial_number')
    )
    op.create_index(op.f('ix_racks_id'), 'racks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_racks_id'), table_name='racks')
    op.drop_table('racks')
    # ### end Alembic commands ###
